# Generated by Django 3.2.4 on 2021-07-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_main_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Link',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='Tell',
            field=models.TextField(default='-'),
        ),
    ]
