# Generated by Django 3.2.5 on 2022-01-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220103_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='insta',
            field=models.CharField(default='-', max_length=60),
        ),
    ]
