# Generated by Django 3.2.5 on 2022-02-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_manager_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
