# Generated by Django 3.2.5 on 2022-01-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
