# Generated by Django 3.2.4 on 2021-07-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_text', models.TextField()),
                ('body_text', models.TextField()),
                ('date', models.CharField(max_length=12)),
                ('pic', models.TextField()),
                ('Writer', models.CharField(max_length=50)),
            ],
        ),
    ]
