# Generated by Django 3.2.5 on 2021-08-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.CharField(default='00:00', max_length=12),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=12),
        ),
    ]
