# Generated by Django 3.2.5 on 2021-08-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_ocatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
